### ISSUE TITLE
Map Point tool issues (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#293]
@nfeuerstein My apologies. I thought I had submitted this issue last night when I had submitted the same issue for the ArcGIS Pro addin.

Tested build 18 Jan 2017 12:25 (#1140).

When the Map Point tool is disabled, the cursor icon does not change back to the cursor icon that was set before the Map Point tool was enabled.

FYI: All other behavior is what I would expect:
- When tool tab is clicked, the Map Point tool is disabled by default.
- User clicks the tool to enable.  Result: the tool is enabled; the look of the button changes to indicate that's it's active; the cursor icon changes to the crosshair. (other behavior is the same...i.e. interact with map, etc).
- User clicks the tool to disable. Result: the tool is disabled; the look of the button changes to indicate that's it's active; just need the cursor icon to be changed back to what it was before the Map Point tool was enabled.

**Comment by nfeuerstein** [comment]
@elinz can you test this again?  I believe @dhagens fixed this with a pull request this evening.

**Comment by elinz** [comment]
Yep. I will login and test right now.

-------- Original message --------
From: Natalie Feuerstein
Date:01/18/2017 9:14 PM (GMT-08:00)
To: Esri/coordinate-conversion-addin-dotnet
Cc: Eric Linz , Mention
Subject: Re: [Esri/coordinate-conversion-addin-dotnet] Map Point tool issues (ArcMap) (#293)


Assigned #293<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Esri_coordinate-2Dconversion-2Daddin-2Ddotnet_issues_293&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=2ZpT4vzBgD3Uq0Qu1_1lvg&m=ndTE_OkTFqWeEBQG_-6v0BFs46vGbf8gVy5b6wLJ_VQ&s=VzXpmhusS0cLY5RDHPIpHo6KOAc-PQm4bULeFBMbQwk&e=> to @elinz<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_elinz&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=2ZpT4vzBgD3Uq0Qu1_1lvg&m=ndTE_OkTFqWeEBQG_-6v0BFs46vGbf8gVy5b6wLJ_VQ&s=x84HHqvwzSz7DJjWu2yIDNsE1HGkhQJqZ4shG_Bkgtw&e=>.

-

**Comment by elinz** [comment]
@nfeuerstein Coordinate Conversion still crashes in latest build, but the Map Point tool issue in Distance Direction was fixed (https://github.com/Esri/distance-direction-addin-dotnet/issues/291), so it looks promising that the Map Point tool issue in Coordinate Conversion was fixed and I can verify when the crash issue #292 is fixed.

**Comment by dhagens** [comment]
@elinz, this is ready for testing

**Comment by nfeuerstein** [comment]
@elinz has this been tested?

**Comment by elinz** [comment]
@nfeuerstein Tested previous build and it wasn't working. Maybe it was timing of build with the merge. Now that another build is available I'm testing it right now.

**Comment by elinz** [comment]
@dhagens @nfeuerstein @kgonzago Tested in the last two builds which were after the merge and this fix isn't working. In fact there are more issues now.

When I submitted this issue, the Map point tool on CC was disabling; the only thing it needed was the cursor to change from the crosshairs to whatever it was before the Map point tool was enabled; however, I can't even disable the Map point tool now.

Assigning back to @dhagens

**Comment by dhagens** [comment]
I'll have to test with the toolbar because everything is working fine at the component level

**Comment by dhagens** [comment]
@elinz, I verified that the current build is not working as it should in the Toolbar.  Could you test the tool at the component level to see if it is working correctly as I am seeing?

**Comment by elinz** [comment]
@dhagens This may be a problem. I'm trying to run the Jenkins build to build the CC at the component level but it's failing.

**Comment by nfeuerstein** [comment]
verified with Hagens that its working at the component level
somethings happening at the single add-in and/or with Jenkins thats causing it to not behave the same
Kevin is going to look into it in a bit and Hagens will reach out the Kevin in case he needs anything

**Comment by dhagens** [comment]
@kgonzago, I have a PR to review and merge.  I moved the IsToolActive property to the ArcMapTabBaseViewModel and removed it from the ConvertViewModel.  I don't know if this might be causing issues in the single addin or not.  Kick off a new build after the merge and let me know if it changes anything.  Everything still seems to work properly at the component level.

**Comment by kgonzago** [comment]
@dhagens PR #299 was merged. I also confirmed your latest change in the single add-in works. Map tool now shows with a cross-hair cursor and disables appropriately.

Once build is done, @elinz can you confirm?

**Comment by elinz** [comment]
@dhagens @nfeuerstein @kgonzago I'll start a Jenkins build now.

**Comment by elinz** [comment]
@dhagens @nfeuerstein @kgonzago Tested the single addin build 19 Jan 2017 19:11 Build Number 1159 and the Map Point tool on coordinate conversion still can't be disabled.

**Comment by nfeuerstein** [comment]
@ACueva could this be a Jenkins issue?

**Comment by ACueva** [comment]
@nfeuerstein not likely.  Jenkins hasn't changed the build process for the single addin since @kgonzago and I implemented it.  I'll log in a few and double check directly from the Jenkins build location to make sure we are both pulling from the correct repo, and correct branches.

**Comment by ACueva** [comment]
Just checked.  Jenkins appears to be pulling from the correct repositories and branches.

**Comment by nfeuerstein** [comment]
@kgonzago @dhagens can you take another look?  @elinz is still seeing an issue with the map point tool in a build he kicked off after the merge last night.

**Comment by kgonzago** [comment]
@nfeuerstein @elinz Good news. Issue fixed. @dhagens will fold in changes in the next build.

**Comment by elinz** [comment]
@dhagens @kgonzago @nfeuerstein Great. I will start another Jenkins build.

**Comment by dhagens** [comment]
I already started one

**Comment by dhagens** [comment]
@elinz @nfeuerstein @kgonzago , I tested the addin in build 1166 and all is working.  Can you close this issue before the War room meeting?  The build failed on documentation but the addin was created successfully.

**Comment by elinz** [comment]
@dhagens @nfeuerstein @kgonzago I'm going to grab the addin from the dated build folder and not from "current" and test that. I will do that right now.

**Comment by elinz** [comment]
@dhagens @nfeuerstein @kgonzago Verified fixed on build 20 Jan 2017 number 1167. Closing issue. Thanks for getting this fixed.

**Comment by nfeuerstein** [comment]
YEEEESSSS!!!
