### ISSUE TITLE
Importing an open .csv file causes application to crash

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#407]
#### Tasks to be done June 6th 2018
- [x] Verify CMS issues addressed in CC and MT
-----------------------

**Background:** 

Users at times need to be able to import and export files such as tables into ArcGIS Pro with the file already opened by another application. 

**Current State:** 
If you have a csv file open in excel and try to import the same file into ArcMap or ArcGIS Pro the application crashes.

**Expected Behavior:** 
A user can import any file no matter if it is opened by another application or not. The applications to be aware of being opened by a user: 

NotePad++
Notepad
Wordpad
Excel

**Comment by csmoore** [comment]
I have not seen this happen with notepad, but definitely with Excel which locks the file - here is one (of many) workaround(s) when this is ready to work on:

```csharp
        // Somewhat hack-ish - needed check for when file is locked or can't be opened
        // (e.g. because of open/being viewed somewhere else-like Excel)
        public bool IsFileOpenable(string filePath)
        {
            try
            {
                using (File.Open(filePath, FileMode.Open)) { }
            }
            catch (IOException ex)
            {
                System.Diagnostics.Trace.WriteLine("ERROR: " + " Message: " + ex.Message + 
                    " Could not open file : " + filePath);
                return false;
            }

            return true;
        }
```

**Comment by topowright** [comment]
Verifed this has now been fixed in our version for ArcGIS Pro 2.1

**Comment by lfunkhouser** [comment]
@topowright This issue still has the task labels on it - This issue still requires a doc update and should not be "Done" http://solutions.arcgis.com/defense/help/coordinate-conversion/resources/release-notes.htm
